# Generated by Django 5.1.7 on 2025-03-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='option',
            field=models.CharField(blank=True, choices=[('plus_profile', 'プラスプロフィール')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.CharField(blank=True, choices=[('standard_1m', 'Standard 1ヶ月'), ('standard_3m', 'Standard 3ヶ月'), ('standard_6m', 'Standard 6ヶ月'), ('standard_12m', 'Standard 12ヶ月')], max_length=20, null=True),
        ),
    ]
