# Generated by Django 5.1.7 on 2025-04-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_option_alter_payment_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('plan', 'プラン'), ('option', 'オプション')], help_text='plan or option', max_length=10)),
                ('code', models.CharField(help_text='Payment.plan や Payment.option に対応する文字列', max_length=20, unique=True)),
                ('name', models.CharField(blank=True, help_text='表示用の名前', max_length=100, null=True)),
                ('base_days', models.IntegerField(default=0, help_text='基本日数(例: standard_3mなら90, plus_profileなら30)')),
                ('extra_days', models.IntegerField(default=0, help_text='キャンペーンなどでさらに延長する日数')),
            ],
        ),
    ]
