# Generated by Django 5.1.7 on 2025-03-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A型'), ('B', 'B型'), ('O', 'O型'), ('AB', 'AB型')], max_length=2, null=True),
        ),
    ]
