# Generated by Django 5.1.7 on 2025-03-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
