# Generated by Django 5.1.7 on 2025-03-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_plan_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='option_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sexual_pref',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M')], max_length=1, null=True),
        ),
    ]
