# Generated by Django 5.1.7 on 2025-03-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_latitude_userprofile_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sexual_object_pref',
            field=models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性')], max_length=10, null=True),
        ),
    ]
