# Generated by Django 5.1.7 on 2025-04-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_gender_userprofile_sexual_object_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'フリープラン'), ('standard', 'スタンダード')], default='free', max_length=10),
        ),
    ]
