# Generated by Django 5.1.7 on 2025-04-01 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_footprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.SlugField(unique=True)),
                ('field_label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'テキスト'), ('select', 'セレクト'), ('radio', 'ラジオ')], max_length=20)),
                ('field_choices', models.TextField(blank=True, help_text='セレクトやラジオの場合、改行区切りで選択肢を列挙')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profilefield')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'field')},
            },
        ),
    ]
