# Generated by Django 5.1.7 on 2025-04-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'テキスト'), ('select', 'セレクト'), ('radio', 'ラジオ'), ('checkbox', 'チェックボックス')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
