# Generated by Django 5.2 on 2025-04-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefield',
            name='category',
            field=models.CharField(choices=[('normal', '通常'), ('plus', 'プラス')], default='normal', max_length=10),
        ),
    ]
