# Generated by Django 5.2 on 2025-04-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profilefield_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefield',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sexual_pref',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
