# Generated by Django 5.2 on 2025-04-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_profilefield_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefield',
            name='category',
            field=models.CharField(choices=[('normal', '通常'), ('plus', 'プラス')], default='normal', max_length=10),
        ),
    ]
