# Generated by Django 5.2 on 2025-04-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profilefield_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lciq',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
