# Generated by Django 5.2 on 2025-04-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userprofile_lciq'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefield',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
