# Generated by Django 5.2 on 2025-05-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_profilefield_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='lciq',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lciq_image',
            field=models.ImageField(blank=True, null=True, upload_to='lciq', verbose_name='LCIQ診断スクショ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lciq_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='LCIQスコア'),
        ),
    ]
