# Generated by Django 5.2 on 2025-05-28 05:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_userprofile_lciq_userprofile_lciq_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.UserProfile.avatar_path),
        ),
    ]
