# Generated by Django 5.2 on 2025-06-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_doc_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_docs', verbose_name='本人確認書類（表面）'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_doc_verified',
            field=models.BooleanField(default=False, verbose_name='書類確認済み'),
        ),
    ]
