# Generated by Django 5.2 on 2025-07-14 07:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_verificationsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('abuse', '暴言・ハラスメント'), ('spam', 'スパム行為'), ('scam', '詐欺・金銭要求'), ('harass', 'ストーカー・しつこい連絡'), ('illegal', '違法・不適切コンテンツ')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', '未対応'), ('ACTION_TAKEN', '対応済み')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('reporter', 'reported', 'reason', 'created_at'), name='uniq_daily_report')],
            },
        ),
    ]
