# Generated by Django 5.2 on 2025-07-15 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_block'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='verificationsubmission',
            index=models.Index(fields=['user', 'status', 'doc_type'], name='core_verifi_user_id_e3a429_idx'),
        ),
    ]
