# Generated by Django 5.2 on 2026-02-25 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_verificationsubmission_core_verifi_user_id_e3a429_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender_pref', models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性')], max_length=10, null=True)),
                ('must_verified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceFieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('must', 'must'), ('bonus', 'bonus')], default='bonus', max_length=10)),
                ('weight', models.PositiveSmallIntegerField(default=10)),
                ('desired_value', models.TextField(blank=True, default='')),
                ('match_type', models.CharField(choices=[('eq', 'eq'), ('contains', 'contains')], default='eq', max_length=10)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_rules', to='core.profilefield')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_rules', to='core.userpreference')),
            ],
            options={
                'unique_together': {('preference', 'field')},
            },
        ),
    ]
