# Generated by Django 5.2 on 2026-02-25 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_userpreference_preferencefieldrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('must', 'must'), ('bonus', 'bonus')], default='bonus', max_length=10)),
                ('weight', models.PositiveSmallIntegerField(default=10)),
                ('desired_value', models.TextField(blank=True, default='')),
                ('match_type', models.CharField(choices=[('eq', 'eq'), ('contains', 'contains')], default='eq', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_rules', to='core.profilefield')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.matchingruleset')),
            ],
            options={
                'ordering': ['-weight', 'id'],
                'unique_together': {('ruleset', 'field')},
            },
        ),
    ]
