# Generated by Django 5.2 on 2026-02-25 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_matchingruleset_matchingrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='PreferenceFieldRule',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
